### ISSUE TITLE
vox_nav is not building , how to get this grid_map_cmake_heplers packgae ?

### ISSUE THREAD

**Issue by BADAL244** [NMBURobotics/vox_nav#10]
stderr: archived_vox_nav_grid_map                             
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "Findgrid_map_cmake_helpers.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "grid_map_cmake_helpers", but CMake did not find one.

  Could not find a package configuration file provided by
  "grid_map_cmake_helpers" with any of the following names:

    grid_map_cmake_helpersConfig.cmake
    grid_map_cmake_helpers-config.cmake

  Add the installation prefix of "grid_map_cmake_helpers" to
  CMAKE_PREFIX_PATH or set "grid_map_cmake_helpers_DIR" to a directory
  containing one of the above files.  If "grid_map_cmake_helpers" provides a
  separate development package or SDK, be sure it has been installed.

---
Failed   <<< archived_vox_nav_grid_map [0.64s, exited with code 1]
Aborted  <<< vox_nav_msgs [0.71s]

**Comment by jediofgever** [comment]
Hello,
Apologies for the late response. 
Currently, I am adding new features and haven't properly set up a flow to handle all dependencies. 

You can get vox_nav itself and other core [dependencies](https://github.com/NMBURobotics/vox_nav/blob/foxy/underlay.repos ) by vcstool. 

Have a look at [here](https://vox-nav.readthedocs.io/en/latest/getting_started/index.html). These are a bit outdated instructions but are good references on how to build vox_nav. 

First get repos then build OMPL and Casadi;

```bash
mkdir -p ~/ros2_ws/src
cd ~/ros2_ws
source /opt/ros/foxy/setup.bash
wget https://raw.githubusercontent.com/jediofgever/vox_nav/foxy/underlay.repos
vcs import src < underlay.repos
rosdep install -y -r -q --from-paths src --ignore-src --rosdistro foxy
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DWITH_IPOPT=true --packages-select casadi ompl
sudo cp install/ompl/lib/libompl.so* /usr/local/lib/
sudo cp install/casadi/lib/libcasadi.so* /usr/local/lib/
sudo rm -rf src/ompl/
sudo rm -rf src/casadi/
```
Then build vox_nav itself;

```bash
source /opt/ros/foxy/setup.bash
cd ~/ros2_ws
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release --packages-skip-regex archived --packages-skip ompl casadi vox_nav_openvslam vox_nav_cupoch_experimental
source ~/ros2_ws/install/setup.bash
```


`grid_map_cmake_helpers` is an external dependency for an archived package of vox_nav, it is better not to build the archived packages as they are not in use. 

Hopefully, you will be able to build vox_nav with the above command. 

There is a robot model [here](https://github.com/jediofgever/botanbot_sim.git), that you can use to test some features of vox_nav.  You can send navigation commands to this robot with an RQT plugin, [here](https://vox-nav.readthedocs.io/en/latest/running_project/index.html)
you will find some guidance on how to do so, note I wrote these instructions some time ago, so things might look slightly different. 

Feel free to comment if you are having trouble. 
Best,

**Comment by jediofgever** [comment]
Closing this for now but,
Feel free to comment.
