### ISSUE TITLE
Visual servoing as one Nav strategy?

### ISSUE THREAD

**Issue by samuk** [NMBURobotics/vox_nav#11]
Complete ROS newbie so please excuse any stupid questions.

I like this visual servo strategy as [demonstrated in Agribot](https://github.com/PRBonn/agribot/blob/master/doc/api/agribot_navigation.md#navigation-in-agribot)

![visual servo](https://camo.githubusercontent.com/148006f5957ec3203e3571b3f0b7027db537913fac9b83d8d0c6a291de172ca3/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f46495253455570586f413853665f563f666f726d61743d6a7067266e616d653d39303078393030)

Could a similar approach be used, using vox_nav to handle the higher level path planning/ waypoint stuff & turns? Then adopting a visual servo approach when correctly situated in a crop row?

Specifically, I was interested in using this [Tensorflow model](https://github.com/ANI717/ANI717_Robotics#readme) when in a crop row

 ![tensorflow](https://github.com/ANI717/ANI717_Robotics/raw/main/Robot%20Workspace.png)

Subscribing to /cmd_vel [from this ROS2 code](https://github.com/mgonzs13/ros2_rover/blob/a12f773d32d3b8ae1ec08c8e8c0633ba6605e3c5/rover_motor_controller_cpp/src/motor_controller/vel_parser_node.cpp#L45) for the Ackerman driven[ Mars rover Tenacity/Sawppy](https://github.com/jetdillo/Sawppy_Rover) & [Upgrading to BLDC motors](https://github.com/mgonzs13/ros2_rover/issues/2)

**Comment by jediofgever** [comment]
Is the system required to create plans in-between waypoints(the known coordinates)?
 
> Could a similar approach be used, using vox_nav to handle the higher level path planning/ waypoint stuff & turns? Then adopting a visual servo approach when correctly situated in a crop row?

My interpretation is that VisualServoing together with a `controller` provides `cmd_vel` in-between waypoints and these commands drive the robot, but I am not sure if there is an actual path plan in between waypoints as reference. If so I would suggest you use [navigation2](https://github.com/ros-planning/navigation2), there is a waypoint follower package that is well written and tested for this purpose.

vox_nav currently have a behavior tree node named [vox_nav_pose_navigator](https://github.com/NMBURobotics/vox_nav/tree/foxy/vox_nav_pose_navigator), which is an action that drives the robot to a single pose, if you want more than one pose, which is the waypoint stuff you mention, there needs to be an additional node/action for that which vox_nav lacks at the moment, I do have a plan to add something like `vox_nav_waypoint_navigator` and implement it with behavior tree, but I can't tell for sure when this can be added.

**Comment by jediofgever** [comment]
For future reference; 
waypoint following (gps and normal) are now implemented with behaviour trees in vox_nav.
