### ISSUE TITLE
Integration with ROS1?

### ISSUE THREAD

**Issue by Quest2GM** [NMBURobotics/vox_nav#13]
Hi,

I was wondering if there is any chance that this will work with ROS Melodic? Or do you only have implementations for ROS2?

Thanks,
Quest2GM

**Comment by jediofgever** [comment]
Hi, 

In the current state no, with considerable amount of effort it can be back ported to ROS1.
Though this will not be done as it does not really bring enough benefits to long term goals of this project. Depending on your use-case, you may run vox_nav on a seperate machine with ROS2 humble, as this is a navigation framework, there are certain ros topics such as, odometry, cmd_vel ... etc that needs to be flowing between robot and the navigation framework, you may opt for ros1_bridge, this is still quite some work to configure. 
P.S unfortunately I am not too optimistic about this.
