### ISSUE TITLE
how can I start the vox_nav

### ISSUE THREAD

**Issue by MoZhenJ** [NMBURobotics/vox_nav#14]
how can I start the vox_nav in the ros2 of humble? If having example to teach our to start the project. Thank you very much

**Comment by MoZhenJ** [comment]
if the example is botanbot_sim?

**Comment by jediofgever** [comment]
Hi,
The botanbot_sim have useful resources and configuration files for this.

**Comment by MoZhenJ** [comment]
> 
Thank you very much!

**Comment by MoZhenJ** [comment]
> Hi, The botanbot_sim have useful resources and configuration files for this.

Hello, I can successfully open the botanbot_sim, but I can't set the point, and the robot doesn't go.

**Comment by jediofgever** [comment]
Hello, You need to send the goal through botanbot_gui
