### ISSUE TITLE
Dockerfile for humble

### ISSUE THREAD

**Issue by NozomiWyane** [NMBURobotics/vox_nav#15]
Hi there, I am very interested in your project and I want to use it in Docker
I noticed that dockerfile is for foxy not humble, since the document are all for humble
Maybe you can make a new dockerfile for humble? thanks very much!!!!!

**Comment by jediofgever** [comment]
Hello, 
That’s a good point, a dockerfile for the humble will be added eventually for now a source build the way to get started

**Comment by jediofgever** [comment]
Please keep commenting if you encounter an issue. I will close this for now.
