### ISSUE TITLE
Screen froze on colcon build

### ISSUE THREAD

**Issue by AddyPete** [NMBURobotics/vox_nav#16]
Ubuntu Version: 22.04
ROS2 Version: Humble
CPU: AMD Ryzen 7, 6800h
GPU: GTX 3070

Hi there! I was trying to build & install vox nav by following the instructions at [https://nmburobotics.github.io/vox_nav/#/GETTING_STARTED_README] 

Everything in the instruction works flawlessly, but during this command: 
**colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DACADOS_WITH_QPOASES=ON -DACADO_CODE_IS_READY=ON -DWITH_IPOPT=true --packages-skip-regex archive --packages-skip vox_nav_control vox_nav_misc**

My screen froze, I waited for about 10minutes and it's still frozen. I tried adding --exeuctor sequential or --parallel-works 2 flags in the command but still results to frozen screen.

What's seems to be the problem here? Thank you.

**Comment by jediofgever** [comment]
What’s the total RAM of your system ? 
My guess would be that the system is running out of memory on the build of some meaty packages, likely vox_nav_planning. My suggestion would be to add some swap memory in addition to your RAM. 

[Here](https://wiki.crowncloud.net/?How_to_Add_Swap_Space_on_Ubuntu_22_04) you can find a tutorial on this. I would suggest in addition to original memory, you should have 32 GB in total, counting the swap memory. You can track the build process on Ubuntu’s awesome “System Monitor” app, which already comes with installation

**Comment by AddyPete** [comment]
okay, I tested it with my system that has 32GB RAM and it builds successfully. Thank you
