### ISSUE TITLE
Steps after starting vox_nav with botanbot sim

### ISSUE THREAD

**Issue by AddyPete** [NMBURobotics/vox_nav#17]
Hello i successfully launched botanbotsim and vox_nav.

I started **Start Selected Gazebo World with vox_nav** (I choosed uneven world)
Next, is I opened up rviz2 with the configuration in the botanbotsim bringup.

With that, i can sucessfully control the robot manually using the manual robot jogger, however when I try 
to do send robot pose operation, the robot does not do anything.

I tried X: 10 Y:10 Deg: 0 then clicked on **Send Robot to Pose** since I assume the starting pose is X:0 Y: 0?
![Screenshot from 2023-10-16 15-56-32](https://github.com/NMBURobotics/vox_nav/assets/40378950/8f9a943c-d28a-4d87-a5d8-ef3f2a97f7f8)

it has these logs

![Screenshot from 2023-10-16 15-54-12](https://github.com/NMBURobotics/vox_nav/assets/40378950/483847ac-6430-4d3c-843e-41efa2e45b3c)

What are the proper steps to start voxnav with botanbot sim?
How to get the XY and Deg info of a goal pose in the gazebo world? 

This is the rviz window and gazebo world. As you can see, i successfully launched it. 
![Screenshot from 2023-10-16 15-53-51](https://github.com/NMBURobotics/vox_nav/assets/40378950/81f6de37-3c3f-449f-8a54-2c222a53693c)
![Screenshot from 2023-10-16 15-54-34](https://github.com/NMBURobotics/vox_nav/assets/40378950/9c344d51-2b9d-43a2-ad22-2615c4ef58cf)

**Comment by jediofgever** [comment]
Hello, 
I think the map haven’t been loaded to vox_nav_map_server. 

Can you check the path to the pointcloud map in this file https://github.com/NMBURobotics/botanbot_sim/blob/main/botanbot_bringup/params/vox_nav_uneven_world_params.yaml

you need to adjust the path to your system

**Comment by AddyPete** [comment]
okay it works. Can vox_nav navigation without a pre-loaded map/pointcloud? Like can it do SLAM with navigation at the same time?

**Comment by jediofgever** [comment]
I have mainly used with a prebuilt map that is because a map based localization is quite attractive. If you don't have a prebuilt map or do not want it ' it should be straight forward to create a planner plugin that just draws lines in between consecutive poses. Then use either GPS way point follower or normal map pose way point follower.

**Comment by jediofgever** [comment]
As for slam, vox_nav does not have mapping module. I can suggest you lio-sam it is one of the sota slam method.

**Comment by AddyPete** [comment]
thanks for the response and suggestions
