### ISSUE TITLE
install/ompl/lib/libompl.so* file not present

### ISSUE THREAD

**Issue by Sukhvansh2004** [NMBURobotics/vox_nav#18]
After building the casadi and ompl packages install/ompl/lib/libompl.so* file is not present and hence colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DACADOS_WITH_QPOASES=ON -DACADO_CODE_IS_READY=ON -DWITH_IPOPT=true --packages-skip-regex archive --packages-skip vox_nav_control vox_nav_misc is giving error while buillding vox_nav_utilities.

**Comment by johnny555** [comment]
Looks like this is an issue with the GitHub actions too. They have been failing with the same error for 6 months: 

https://github.com/NMBURobotics/vox_nav/actions/runs/7505512204/job/20434891498#step:5:2096

**Comment by coxep** [comment]
Came here because we are seeing the same build issues, and vox_nav documentation indicates that we should look to github actions as a build reference at the bottom of this page: https://vox-nav.readthedocs.io/en/latest/getting_started/index.html

Our team is considering using vox_nav, but the fact that there have been persistent build issues for so long has us all a bit concerned.

In this specific case, it appears that OMPL no longer installs to the lib directory when built with colcon, but to the share directory:

```
$ find ros2_ws/install -name "libompl.so*"
install/ompl/share/libompl.so.1.6.0
install/ompl/share/libompl.so
install/ompl/share/libompl.so.17
```

**Comment by Sukhvansh2004** [comment]
I tried to move the files from shared folder instead of lib, however still I am facing furthur issues. I am getting the follwoing error while now during colcon build of vox_nav_control and vox_nav_misc. I also tried to build it on humble since things weren't working out on foxy

```shell
/home/sukhvansh/ros2_ws/src/vox_nav/vox_nav_utilities/include/vox_nav_utilities/planner_helpers.hpp:20:10: fatal error:ompl/base/samplers/ObstacleBasedValidStateSampler.h: No such file or directory
   20 | #include <ompl/base/samplers/ObstacleBasedValidStateSampler.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/elevation_state_space.dir/build.make:76: CMakeFiles/elevation_state_space.dir/src/elevation_state_space.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:255: CMakeFiles/elevation_state_space.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< vox_nav_utilities [57.5s, exited with code 2]

Summary: 4 packages finished [1min 36s]
  1 package failed: vox_nav_utilities
  3 packages had stderr output: ACADO vox_nav_msgs vox_nav_utilities
  5 packages not processed
```

**Comment by Sukhvansh2004** [comment]
I also got the below error during rosdep install

```shell
rosdep install -y -r -q --from-paths src --ignore-src --rosdistro humble --skip-keys="cartographer-ros cartographer_ros"
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
vox_nav_control: Cannot locate rosdep definition for [casadi]
vox_nav_map_server: Cannot locate rosdep definition for [OCTOMAP]
archived_vox_nav_openvslam: Cannot locate rosdep definition for [openvslam]
Continuing to install resolvable dependencies...
executing command [sudo -H apt-get install -y -qq ros-humble-fast-gicp]
E: Unable to locate package ros-humble-fast-gicp
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y -qq ros-humble-fast-gicp] failed
  apt: Failed to detect successful installation of [ros-humble-fast-gicp]
```

**Comment by jediofgever** [comment]
ok, hopefully I would be able to find some time to fix CI and you can take that as a reference.

**Comment by tillb98** [comment]
Has anyone been able to resolve this issue? When attempting to install vox_nav in humble, I continue to encounter the issues described.

**Comment by Sukhvansh2004** [comment]
Is this issue resolved now?
