### ISSUE TITLE
ObstacleBasedValidStateSampler.h no such file or directory

### ISSUE THREAD

**Issue by aserbremen** [NMBURobotics/vox_nav#19]
Hey I am following the [installation guide](https://vox-nav.readthedocs.io/en/latest/getting_started/index.html), where i exchanged the foxy parts to humble as I am using Ubuntu 22.04. 

`
colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DACADOS_WITH_QPOASES=ON -DACADO_CODE_IS_READY=ON -DWITH_IPOPT=true --packages-skip-regex archive --packages-skip vox_nav_control vox_nav_cupoch; \
`

The above command fails with 
```
--- stderr: vox_nav_utilities                              
In file included from /home/andi/code/cpp/vox_nav/src/vox_nav/vox_nav_utilities/src/planner_helpers.cpp:17:
/home/andi/code/cpp/vox_nav/src/vox_nav/vox_nav_utilities/include/vox_nav_utilities/planner_helpers.hpp:20:10: fatal error: ompl/base/samplers/ObstacleBasedValidStateSampler.h: No such file or directory
   20 | #include <ompl/base/samplers/ObstacleBasedValidStateSampler.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I had to set `set(OMPL_INCLUDE_DIRS /path/to/vox_nav_ws/install/ompl/include/ompl-1.6)` in `src/vox_nav/vox_nav_utilities/CMakeLists.txt` and `src/vox_nav/vox_nav_planning/CMakeLists.txt`

**Comment by jediofgever** [comment]
Thank you for providing your solution. 
It seems that the `colcon` tool and `ompl` had a breaking change, causing this error. 
Now, instead of source build, we use ompl-dev binary install; you may check the steps Github actions for a successful build.
