### ISSUE TITLE
Traversability map is empty, cannot refine plan. 

### ISSUE THREAD

**Issue by aserbremen** [NMBURobotics/vox_nav#20]
Thanks for your work in 3d navigation. 

I am trying to run the botanbot sim in uneven world with vox_nav and set a goal pose directly in front of the robot x=10.0m. I set the pcd pose to z=-0.7m so that the botanbot is roughly on the surface displayed in rviz. When I `SEND ROBOT TO POSE` the robot moves roughly in the correct direction however the botanbot always ends up somewhere random about the actual goal pose but usually a couple meters away from it. One example is given in the screenshot. What am I missing. The terminal says the traversability map is missing, but I dont know where to start fixing this. 
![Screenshot from 2024-05-30 18-18-59](https://github.com/NMBURobotics/botanbot_sim/assets/56029245/b5ade9dd-e5fb-454c-b80f-f4078ce0f705)

**Comment by jediofgever** [comment]
I guess a way forward would be to disable the plan refiner plugin. 
Take a look at [here](https://github.com/NMBURobotics/vox_nav/blob/humble/vox_nav_map_server/config/osm_map.yaml)

We Don't have a parameter to disable it from the YAML config file, but you can easily change it in the code. 

https://github.com/NMBURobotics/vox_nav/blob/b9d68e7fefffe4ff9bb9fe7fd9d594a192ce008e/vox_nav_control/src/controller_server.cpp#L142

You may comment on the above line. I'm not sure which controller plugin you are using, but I recommend starting with Casadi Controller plugin.

**Comment by aserbremen** [comment]
Thanks for the quick reply. I disabled the path refiner plugin and tried to run the world again and set a slightly more involved pose (x=4, y=1, theta=15°). The robot seems to end up in the correct goal pose in the odom frame, but the odom frame is also shifting and not staying relatively close to the initial pose. 

I created a screen recording, which might help to better understand what's happening for you. The `.mkv` file can be downloaded [here](https://seafile.zfn.uni-bremen.de/f/20cccb7fabba4fcca263/) 

I get one error at the beginning during start up but I am not sure whether this is relevant for running botanbot sim. 
`[gzserver-1] Node::Advertise(): Error advertising topic [uneven_world/full_sensor_suite/wide_angle_camera_link/wide_angle_camera/image]. Did you forget to start the discovery service?`

For the configuration see the attached `.txt` file. It's actually .yaml but github doesn't allow yaml. 
[vox_nav_uneven_world_params.txt](https://github.com/user-attachments/files/15729143/vox_nav_uneven_world_params.txt)
