### ISSUE TITLE
navigation with lidar sensor only

### ISSUE THREAD

**Issue by rvxfahim** [NMBURobotics/vox_nav#21]
Hi i have generated a pcd map using lioslam and at the current state of my project is that I can perform localization using lidar with the loaded pcd map. I am looking for some guidance as to whether I can use your repo to load my pcd map and use only lidar to perform navigation. I dont have a GPS as it is an indoor map.

**Comment by jediofgever** [comment]
This should be possible, albeit not out-of-the-box, as vox_nav is primarily aimed for outdoor scenarios where you typically have a GPS. Can you please link your pcd point cloud map for reference?

**Comment by METEORITENMAX** [comment]
Hi, i want to use vox nav on a Spot from BostonDynamics without GPS too. Before i would like to have it running in our webots simulation world. 

Here our Simulation world: https://github.com/MASKOR/webots_ros2_spot
Most of the Interfaces/ROS Topics are same to our/the real one.

This is a forked version of the octomap version, we use in simulation and on the real Spot:
https://github.com/RRL-ALeRT/octomap_mapping

Normally we do not create a pcd map and only visualize the octomap in rviz2. Most of the time we do SLAM teleoperated or by running predefined waypoints or navigation2..

For the octomap we only use RealSense D435, no lidar. And as you can see here, the/our odometry is really accurate and stable:
https://www.linkedin.com/posts/alert-the-fh-aachen-legged-rescue-team_ros2-robocup-software-stack-for-spot-on-steamdeck-activity-7092896550284103680-2KHG?utm_source=share&utm_medium=member_desktop

I will create an octomap in our webots simulation and send you a link, but normally we have the extension .bt or .ot, but maybe i also can do .pcd ..
I would appreciate if you have more hints to get it running, thanks!

**Comment by rvxfahim** [comment]
> Can you please link your pcd point cloud map for reference?

[pcd_files.tar.gz](https://github.com/user-attachments/files/16058171/pcd_files.tar.gz)

just a note: I have made this pcd file from gazebo simulation by loading my own 3d model of a simple garage.
